### PR TITLE
Desk Rental Clarification

### PR DESCRIPTION
**Pull request by andrewbolster**
From [This](https://docs.google.com/presentation/d/18Gbpx3m7K2IdUzjPjvuPLP4QbLGaG3riKGkQPGybypQ/edit#slide=id.p) discussion at the [June Town Hall](https://docs.google.com/document/d/1koEeVoujnw3RIsW0fy_TxjXLvebNwtC0V7OWSbBGKZY/edit).

Implications: 
* Clear awareness of what desks are rented/not
* Clear statement of what 'clear desk policy' means, including statement that any member can move things left at peoples behinds.
* Workshop desks now have an actual policy against them instead of the current 'first come, whatever you like'

Proposal:
* Ratification is already implied through Town Hall clearance, however propose a 'cool off period' between now and the next town hall (2nd July), after which the policy will be enforced.

### CODE REVIEW

**Comment by martinnaughton** [comment]
Looks good. Just 2 desks thought. What about the tools desk at the far back with the drill. Can i use that desk?

**Comment by martinnaughton** [comment]
Also what if I make a desk or bring my own desk? Does that count?

**Comment by martinnaughton** [comment]
If i put my equipment under the desk does that count as renting the desk? I some equipment at home I would like to bring in to store

**Comment by Stealthii** [comment]
I believe clear desk policy should apply to both the desk and underneath/around it. We might want to clarify that better in the clarification.

**Comment by andrewbolster** [comment]
@Stealthii @martinnaughton can you review latest commit re under-desk?

**Comment by andrewbolster** [comment]
@martinnaughton as per farsetlabs.github.io/about/floor_plan.png, the two rentable/hot workshop desks are the back 'tool' bench and one of the window benches.

**Pull request merged**
