### PR TITLE
Policy Updates:

### PR DESCRIPTION
**Pull request by andrewbolster**
* Added Reserves policy in line with
[recommendations](https://www.charitycommissionni.org.uk/media/1554/20180320-ccni-ego63-developing-a-reserves-policy-v10.pdf)
* Updated links across policies to drop the `.html` suffix
* Added contextual section links
* Fixed Address Formatting in CoC
* Added Directors/NEMS/Members time committment expectations
* Extended "Access" section to include codes, passwords, etc (ass covering)
* Minor formatting fixes

### CODE REVIEW

**Review by dylwylie — COMMENTED** [review]
+1 but you added the "For significant purchases" bit twice :D?

**Comment by chris18890** [comment]
LGTM :+1:

**Review by dylwylie — DISMISSED** [review]

**Comment by awflwafl** [comment]
@andrewbolster why does this need a Town Hall?

**Comment by andrewbolster** [comment]
@awflwafl Technically it no longer does, as it was discussed at the Town Hall on monday, where the changes made in e750379 were requested.

**Comment by awflwafl** [comment]
@andrewbolster ok. I'm still curious, why would this have needed a Town Hall?

**Comment by andrewbolster** [comment]
@awflwafl the fact that significant changes to a more than 6 month old pull request were made after review at a Town Hall indicate that Town Hall was necessary; 

By convention, any policy changes are reviewed at Town Hall for open, 'public' comment, critique, and assent.

Considering that this PR touched on our Code of Conduct and Expenses Policies, including the ratification of a new (but operationally adopted) Charitable Reserved Policy, as well as minor changes to the overall Rules and Policy pages and the, since reverted, changes to the Ops Manual, it would be a hard sell to say that these were 'minor policy changes' that could just be passed through.

Making all these changes without community governance, transparancy, and oversight would have been against established convention.

**Review by awflwafl — COMMENTED** [review]
Ready to approve, pending response to suggestions. 

It was difficult and time consuming to review the groups of unrelated proposals in this pull request as a single changeset. In the future we should create one pull request per proposal instead which is common practice for version controlled projects.

It's important to note that the **reserves policy** is a copy-paste from the latest [Trustee Annual Report](https://apps.charitycommission.gov.uk/ccni_ar_attachments/0000102754_20190228_TAR.pdf). Hence, I'm happy to replicate out stance on holding reserves to the website.

As for the **expenses policy** proposal, I've only seen this process being used twice which is a better measurement than saying we've been doing it for 6 months. It's a good way to keep us financially responsible so I agree with making it our ongoing practice.

**Other changes** across the website are okay to get deployed as well.

**Comment by awflwafl** [comment]
If it's convention, that makes sense. As you mentioned yesterday Town Halls being a forum to let people _comment_ on organisational changes is fair and a great way to be transparent.

My primary concern was that Town Halls can't be a sign-off point for specifying "job requirements" for directors/managers who have existing agreements about their commitments. Those types of changes must be signed off by the people that make the commitments.

As a side note; saying that changes were made after a Town Hall is a bit of a misrepresentation given that those changes were requested by myself, as a director.

**Comment by oibind** [comment]
It fits the ethos of a hackerspace better to be as nonhierarchical and transparent as possible, no?

**Comment by awflwafl** [comment]
@oibind yes, I'm all for the transparency. I'm against increasing the workload for volunteers without their agreement.

**Review by dylwylie — APPROVED** [review]

**Comment by awflwafl** [comment]
There were still open question and requests for changes on this pull request, so we'll need to address those in the near future.

**Pull request merged**
