### PR TITLE
Add Stripe pricing table to homepage

### PR DESCRIPTION
**Pull request by robertwpaul**
## Description

Add a Stripe pricing table to the homepage. This is for demo purposes so uses the test mode page; you can sign up using [test cards](https://docs.stripe.com/testing#international-cards) and edit your test subscription on the [customer portal](https://billing.stripe.com/p/login/test_cN29CO6iJ9Bz6JibII).

Other relevant changes:
  - Made the site wider. The current width is narrow enough that the table converts to mobile view.
  - It's too wide for things like the `Donate` page where the buttons are full width, so I limited the width of those buttons.
  - I'm using the rounded buttons in the pricing table, so updated the other buttons on the site to match.

Before | After
--- | ---
image|image

### CODE REVIEW

**Review by chris18890 — APPROVED** [review]

**Comment by chris18890** [comment]
@alistairjcbrown Had merged it to test that things loaded/looked ok, have approved & deployed the other PR to revert. Might be worth splitting the CSS changes & the plans out into separate PRs? @robertwpaul ?

**Comment by alistairjcbrown** [comment]
@chris18890 Did the netlify deploy preview not provide confidence in the loading/appearance? Is there anything we can change on it to provide more confidence?
Just a little panic because merging puts it live, which then breaks the existing membership sign-up flow

**Comment by chris18890** [comment]
@alistairjcbrown I use [NoScript](https://noscript.net/) to block external scripts so wanted to see what was actually required to be loaded :)

When you say it breaks the existing flow, is that due to moving signups from nexudus to stripe? does striope then redirect to nexudus?

**Comment by alistairjcbrown** [comment]
@chris18890 Yes -- this PR removed the links to the live Nexudus subscriptions and replaced them Stripes product table pointing to a Stripe test account.

You can try it out on the demo deployment -- https://deploy-preview-418--dreamy-paletas-cb5e15.netlify.app/ -- using the Stripe [test cards](https://docs.stripe.com/testing#international-cards)

**Pull request merged**
