### PR TITLE
Add store page linked from nav bar

### PR DESCRIPTION
**Pull request by robertwpaul**
Screenshot 2023-02-05 at 16 47 32

### CODE REVIEW

**Comment by chris18890** [comment]
@robertwpaul did you mewan to delete the projects page?

**Comment by robertwpaul** [comment]
> @robertwpaul did you mewan to delete the projects page?

Yeah, to replace it.

**Review by awflwafl — APPROVED** [review]
Thanks!

**Comment by chris18890** [comment]
Oh, Are we not using trello any more?

**Pull request merged**
