### PR TITLE
Add initial work on a clearance policy

### PR DESCRIPTION
**Pull request by philtweir**
Placeholder for clearance text, for property with known owners.

### CODE REVIEW

**Comment by andrewbolster** [comment]
FYI Make sure when you're going through this to check for duplications/redundancies with other policies, particularly the CoC, Donation, and Equipment sections.

**Comment by philtweir** [comment]
@awflwafl good points - I'd left it open for either leaving in situ or moving to communal storage (as in the existing rules), but that creates a potential ambiguity, where something ticketed on Day 0, is moved by, say, a NEM, (or the owner) to communal storage on Day 10 - does it start from scratch as a new item in communal storage, or is it still treated as having been left in an open space for 10 days and counting, or is it treated as if it had been in communal storage for 10 days? And if it's been moved from where it was left before 30 days, does that mean an owner can claim that unreasonably contributed to them forgetting or not noticing? What happens (most likely case) when periodically it moves between different communal storage or open spaces indefinitely? (from someone using their own property and always leaving it lying always in communal space of some sort) Will have a think and suggest a way of covering those cases.

@andrewbolster also fair point - I should probably add a note that this is more an... "Implementation Guideline"... as it should be entirely within the existing rules and CoC, which _roughly_ say "if your property has been left for 30 days unattended and you have been notified, then it may be treated as abandoned" (so there will be duplication, as part of consistency, but this isn't intended to add any rules).

The main purpose from my perspective is to provide a workflow that can be followed without follow-up questions as to (for example):

- whether "notification" covers how they were notified (by Slack, and it's up to people to check their notification settings),

- whether a Director or NEM knowing who owns it or how long it's to be there for counts as "labeled" or means that property will not be disposed of (no, needs a visibly printed Slack handle on Farset Slack),

- whether an individual or Farset gaining money or property through this is taking advantage of a grey area (there is an explicit scheme for reasonably making property communal, or someone else's, with checks and balances, and incentives for implementation)

- if someone doesn't get around to picking something up in 30 days, is that disposed of immediately and ends up in an ill-will cliff-edge? (no, there's 30 days after, where it's no longer handy, but retrievable)

It's worth adding a note that any Director (NEM's can't afaiu) agreeing to property being left over 30 days in an open space or communal storage is responsible for Farset-stickering it appropriately, as it will be disposed of if not. In other words: if someone is told by a senior person that their property won't be disposed of, replacing it shouldn't be the responsibility of either the owner, or a third-party who disposes of it, _if that has been appropriately agreed but not physically stickered_ (otherwise it's not safe to dispose of anything without more checking than it's worth). Relatedly, a clear line on who _can_ agree that, so asking "Bob at Desk 2" isn't a get out clause for storing things indefinitely (presumably just Directors).

Few TODOs for next revision:

- [ ] wording: public storage -> communal storage
- [ ] situation where property is moved to communal space part-way (either by owner or otherwise)
- [ ] common-case scenarios for clarity
- [ ] note on who can mark something as not-to-be-removed
- [ ] "implementation guideline"

Also, will suggest a TL;DR text for putting in the space once this is finalized, so there's no surprises.

**Comment by philtweir** [comment]
* two examples added
* notes on who can prevent removal
* reordered to put locations together, ahead of removal timescales
* renamed from public storage to communal storage
* note this is an Implementation Guideline, rather than a new policy (i.e. taking these steps is compatible with the existing policies already, afaict, but they're vague on a "best acceptable approach", which this defines)

Also note to any Farset members, managers or otherwise: this PR has been referenced on Slack, at Town Halls and management meetings over the last 3.5 months - if there is any feedback, this is _absolutely_ the last opportunity.

**Comment by philtweir** [comment]
@andrewbolster i think that's had enough shout-outs in Town Halls, Slack and otherwise to give adequate feedback over the last 3 months - happy to merge?

**Comment by philtweir** [comment]
Will put together the machinery mentioned (specifically the doc for managing who has what), then will do a PR to link this from the main site rules page.

**Pull request merged**
