### PR TITLE
Track Club Mate stock using GSheet

### PR DESCRIPTION
**Pull request by Dylan1312**

### CODE REVIEW

**Comment by Stealthii** [comment]
I would like to delay this slightly until we tidy up the dependencies in `default.html` - we shouldn't have in-line script tags in Markdown. We can do a fast solution, and then tidy up later for piece of mind (we've less security concerns with a static site to begin with) :+1:

**Comment by Dylan1312** [comment]
Can't find any consensus online about <script> tags in markdown, happy to leave as is or bow to whatever you suggest.

**Comment by andrewbolster** [comment]
Ummm, I'm with @Stealthii on this one, inline jsified html has a weird smell about it, and I've got no idea if this will work on github. Worth a shot though :)

**Comment by Dylan1312** [comment]
jsified html is how you doing dynamic content on a static site ;)

**Comment by andrewbolster** [comment]
I know and I've used it in several places around in the more htmly files. I say go for it even if it smells :smile:

**Comment by Stealthii** [comment]
So it is, apologies @Dylan1312 :grinning:

I am happy to merge this now, with the proviso we revisit more than just this in the due tidy-up.

**Comment by Dylan1312** [comment]
Mucho gracias, Conor's updated the sheet which broke the backend so stock's currently showing as 0. Will fix.

**Pull request merged**
