### PR TITLE
Revert "Pride 2021"

### PR DESCRIPTION
**Pull request by andrewbolster**
Reverts FarsetLabs/farsetlabs.github.io#338

`<satire>`
Happy July everybody, and as is traditional, we expell all the LGBTQI+ people that we publicly permitted to exist for a month and send them back to the reeducation camps
`</satire>`

As always, Farsets [Equality Policy](https://www.farsetlabs.org.uk/about/equality.html) is still in effect. 🏳️‍🌈

### CODE REVIEW

**Comment by andrewbolster** [comment]
Probably more 'friendly' version of this statement is: 

As June turns to July, we take down the flags of celebration, diversity, and equality, not to silence or to diminish, but rather to make sure these flags are just as vibrant when we raise them again next year.

**Review by caolanxyz — APPROVED** [review]

**Review by oibind — APPROVED** [review]

**Comment by oibind** [comment]
Also considering things that have gone on in recent years like that in Chechnya or in the not so distant history with the Nazis, joking about internment camps isn't funny. Remember that the Holocaust may have ended in April 1945 but the false imprisonment of a lot of LGBT people, disabled people, and travelers in the same camps didn't.

**Comment by oibind** [comment]
Not to mention the current ongoing battle to ban conversion therapy in the UK.

**Comment by andrewbolster** [comment]
@oibind you're right, it's inappropriate and poorly timed, I apologise 😔

**Comment by oibind** [comment]
There would never be a right time.

**Comment by andrewbolster** [comment]
@oibind I apologise unreservedly for my stupid comment, you're right, that kind of statement is never appropriate under any circumstances.

**Pull request merged**
