### PR TITLE
Added Club-Mate about page

### PR DESCRIPTION
**Pull request by Stealthii**
Basic Club-Mate about page, with information about what's in the space, and how to order some.

### CODE REVIEW

**Comment by andrewbolster** [comment]
No HTTPS link? :P 

More practically, can you add an image entry to the preamble for easier / sexier sharing? The layout scripts interrogate this field to decide wether to use a image or standard twitter / fb card, and images always work better. 

(30% of the time it will successfully grab 'the right' image any way but most of the time twit/fb usually grab the logo or a header image depending on their whim; this way gives us direct control) 

see facility.md for a example.

**Comment by Stealthii** [comment]
Any site which falls over, or doesn't correctly fix mixed-content doesn't get a free ticket on our site ;) This unfortunately is still the majority.

Noted about image entry.

**Comment by Stealthii** [comment]
@andrewbolster, deployed to beta, but image doesn't appear when pasting https://beta.farsetlabs.org.uk/about/club_mate.html into Facebook, for example. Not sure if expected to or not.

**Comment by andrewbolster** [comment]
Ahhhh, dirty dirty hotlinker; the layout expects image tags to be locally hosted within the asset dir, which makes for some funky urls if you try to set an image:attrib outside the path. 

At this point I'm past caring so either bring the target image into repo or revert back to first, non-image, version and let fb/twit sort themselves out for the time being.

**Comment by Stealthii** [comment]
I'm not a fan of adding more images to the source tree for obvious reasons (will investigate Jekyll's build parameters, but for later discussion), not that hotlinking to another site is ideal either, I saw this as temporary. Shall revert for now, and we'll approach this at a later date. :+1:

**Pull request merged**
