### PR TITLE
pull network config updates from MDWiki

### PR DESCRIPTION
**Pull request by Stealthii**

### CODE REVIEW

**Comment by chris18890** [comment]
same as before, LGTM :+1:

**Comment by Stealthii** [comment]
I'm not keen on this, because I don't see why publishing the port allocation of our switch is useful to the public (apart from mischievous use). I'm a fan of reducing clutter on the website, and personally I vote for this page to be removed altogether.

**Comment by andrewbolster** [comment]
http://www.farsetlabs.org.uk/wiki/#!Network_Port_Allocation.md

This is and has been "public" for a while.

This was discussed in person a couple of weeks ago and I asked you specifically about this before raising the pull request. 

Until there's an actual grown up, collaborative wiki/knowledge base that can be used as a repository for management information, I see no harm in this being included in a low traffic page. 

Agree that this page should be deprecated _after_ completion of [DI-167](https://jira.farsetlabs.org.uk/browse/DI-167)

**Comment by Stealthii** [comment]
I'm not arguing against it's "being made public", I'm arguing against it's inclusion on a site where this information is relevant to maybe 0% of our homepage viewers. Out of all the pages on the old Wiki containing relevant public information, this is not interesting, or relevant, and doesn't need included _anywhere_ until there's a reasonable place to do so. Leave it on the existing Wiki, and migrate it to the new Wiki when/if that happens.

**Comment by andrewbolster** [comment]
Superseded and made irrelevant by http://wiki.farsetlabs.org.uk/index.php/Di/Networking

**Pull request closed without merging**
