### PR TITLE
adding a smile to peoples browsers

### PR DESCRIPTION
**Pull request by andrewbolster**
Add info re Amazon Smile and some minor text updates, as it wasn't exactly clear that we accepted one-shot bacs donations.

### CODE REVIEW

**Comment by Dylan1312** [comment]
We should probably be signposting people to https://www.paypal.com/gb/fundraiser/charity/113209 primarily instead of BACS

Benefit is that it handles Gift Aid for us (and there's also no fees)

**Comment by andrewbolster** [comment]
@Dylan1312 we do? It's literally the [line above](https://github.com/FarsetLabs/farsetlabs.github.io/pull/180/files#diff-6f03e42d6bae7b75ea525bec87eb719fR17)

>Farset Labs is an accredited charity and is eligible to Gift Aid tax relief on one off donations. We are also certified by PayPal as being eligible to take part in their PayPal Giving Fund which absorbs PayPal's normal transaction costs for charitable donations.

**Comment by Dylan1312** [comment]
Yeah but my point is that saying BACs is easier is untrue

**Comment by andrewbolster** [comment]
There; happy @Dylan1312 ? 😂

**Pull request merged**
